# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_one_tree_cpp <- function(r, h, x, mugrid, dichotomous, taugrid, param) {
    .Call(`_SMARTboost_fit_one_tree_cpp`, r, h, x, mugrid, dichotomous, taugrid, param)
}

nlopt_example <- function() {
    .Call(`_SMARTboost_nlopt_example`)
}

