# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitbeta_cpp <- function(r, G, var_epsilon, param, infeaturesfit, dichotomous, mu, tau, dichotomous_i) {
    .Call('_SMARTboost_fitbeta_cpp', PACKAGE = 'SMARTboost', r, G, var_epsilon, param, infeaturesfit, dichotomous, mu, tau, dichotomous_i)
}

