# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sigmoidf_cpp <- function(x, mu, tau, sigmoid, dichotomous) {
    .Call(`_SMARTboost_sigmoidf_cpp`, x, mu, tau, sigmoid, dichotomous)
}

updateG_allocated_cpp <- function(G0, g, G) {
    .Call(`_SMARTboost_updateG_allocated_cpp`, G0, g, G)
}

fitbeta_cpp <- function(r, G, var_epsilon, param, infeaturesfit, dichotomous, mu, tau, dichotomous_i) {
    .Call(`_SMARTboost_fitbeta_cpp`, r, G, var_epsilon, param, infeaturesfit, dichotomous, mu, tau, dichotomous_i)
}

Gfitbeta_cpp <- function(r, h, G0, xi, param, var_epsilon, infeaturesfit, dichotomous, muLogTau, dichotomous_i, G) {
    .Call(`_SMARTboost_Gfitbeta_cpp`, r, h, G0, xi, param, var_epsilon, infeaturesfit, dichotomous, muLogTau, dichotomous_i, G)
}

